_VPATH	+=:$(ROOT)/spi/legacy

PROCOBJ	+= spi_getc_spi1_lib_legacy.o spi_getc_spi2_lib_legacy.o 
PROCOBJ	+= spi_gets_spi1_lib_legacy.o spi_gets_spi2_lib_legacy.o 
PROCOBJ	+= spi_open_spi1_lib_legacy.o spi_open_spi2_lib_legacy.o 
PROCOBJ	+= spi_puts_spi1_lib_legacy.o spi_puts_spi2_lib_legacy.o 
PROCOBJ	+= spi_brg_tbl_lib_legacy.o


