_VPATH	+=:$(ROOT)/timer/source

LIBOBJ	+= open_core_timer_lib.o update_core_timer_lib.o read_core_timer_lib.o write_core_timer_lib.o

PROCOBJ	+= open_core_timer_lib.o update_core_timer_lib.o read_core_timer_lib.o write_core_timer_lib.o


